### ISSUE TITLE
Clean up GPT2 model

### ISSUE THREAD

**Issue by Notgnoshi** [Notgnoshi/research#67]
- [ ] Check for reproducible results
- [ ] Output generation parameters in CSV file #58 
- [ ] Improve logging
- [ ] Clean up differences between model name and path
- [ ] Test with GPT-1
- [ ] Add verbose docstrings
- [ ] Add type hinting
- [ ] Fix markov seeding
- [ ] Break GPT model into more manageable pieces
- [ ] validate the config dictionary #46 
- [ ] Fix script to pick the right language model #37, #55, #48
